### PR TITLE
SLING-9327 fixing dependencies to work with jdk11

### PR DESCRIPTION
**Pull request by tyge68**
@bdelacretaz  I have tested with that and it would solve the issue, note due to compilation issues on jdk11 (1), I had to update the maven surefire plugin. I have tried also to update with latest parent pom , but there I had other issues (missing org osgi dependencies etc...) so that change seems to be the safest.

(1) https://issues.apache.org/jira/browse/LANG-1384

### CODE REVIEW

**Comment by rombert** [comment]
I don't have a strong opinion about this, but maybe we can remove the jaxb dependency?

**Comment by tyge68** [comment]
@bdelacretaz  I also noticed that the osgi core dependency scope was wrong, due to the scope provided, all module that uses teleporter had to also add it as dependency which is not ideal.

**Comment by tyge68** [comment]
> I don't have a strong opinion about this, but maybe we can remove the jaxb dependency?

I don't actually now why it uses that, but as simply adding the dependency would make it work at the moment I rather keep it as it is.

**Comment by tyge68** [comment]
Indeed I tried the commit https://github.com/apache/sling-org-apache-sling-junit-teleporter/commit/9cf6c329304e0168222e3b1a9792a7c4981b99d4 and it helped. Thanks @bdelacretaz  let me know once this is available so I can update my dependencies

**Pull request closed without merging**
