### PR TITLE
SLING-11633 - Compile with Java 11

### PR DESCRIPTION
**Pull request by sufyanharoon**

### CODE REVIEW

**Comment by sufyanharoon** [comment]
@rombert Please review and merge.

**Review by rombert — COMMENTED** [review]
What problem does this solve?

**Comment by sufyanharoon** [comment]
>What problem does this solve?
When using the latest build of teleporter in tests, these dependencies were not coming transitively. When added in tests, it worked. Ideally, these should come transitively as teleporter code only is using them. 

cc: @rombert

**Comment by rombert** [comment]
@sufyanharoon - I'm not an expert of the module here, but I see it's packaged as a bundle as well, so we should not explicitly declare dependencies and rather let OSGi runtime point out what is needed.

But perhaps you are using it differently?

**Comment by rombert** [comment]
@sufyanharoon - I agree that it can be used as a plain jar, but if you build it you will see that it's an OSGi bundle

- https://github.com/apache/sling-org-apache-sling-junit-teleporter/blob/3de6bd052bcb1c7b59bcf6c7a660bc2be5ead532/pom.xml#L24

```
$ cat target/classes/META-INF/MANIFEST.MF | grep 'Bundle-SymbolicName'
Bundle-SymbolicName: org.apache.sling.junit.teleporter
```

Won't your scenario be fixed if you add the two extra jars to the classpath?

**Comment by sufyanharoon** [comment]
@rombert, yes adding the two additional jars to the class path should fix this issue but before we upgraded to Java 11, it used to work seamlessly. This is a side effect of update of Java 11 where we have updated certain dependencies.
As I stated earlier, anyone using latest teleporter will have to add these dependencies in their test class path. For that, the same should be documented on teleporter's [page](https://sling.apache.org/documentation/bundles/org-apache-sling-junit-bundles.html) under upgrade to Java 11 runtime otherwise everyone will struggle with the same issue that faced. 

Do you see any issues in adding these additional jars as dependencies? These will make update to Java 11 and general usage of teleporter seamless.

**Comment by rombert** [comment]
Hm, why did this get closed? I don't remember deleting this branch.

**Pull request closed without merging**
