### PR TITLE
 SLING-11633 - Compile with Java 11

### PR DESCRIPTION
**Pull request by rombert**

### CODE REVIEW

**Comment by rombert** [comment]
@sufyanharoon - I added a small comment on top of your changes from #7 , hope this is fine.

**Comment by sufyanharoon** [comment]
Thanks @rombert. Later on, I had changed the scope to runtime as these are not needed for compile but needed at runtime for tests to run. Similar to Line#98 in the pom. If you could change it, it would be good.

**Comment by rombert** [comment]
Thanks for the revierw @sufyanharoon . I made the additional change now, let me know if that solves the issue completely.

**Comment by sufyanharoon** [comment]
@rombert LGTM.

**Comment by rombert** [comment]
Thanks for your patience @sufyanharoon, I started a release vote: https://lists.apache.org/thread/lfkj8cjfswcp3nnqx3s1mxrmd99rs1wl

**Pull request merged**
